config/routes.rb
Rails.application.routes.draw do
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'

  devise_for :users, :controllers => { 
    registrations: 'registrations',
    invitations: "invitations" 
  }

  resources :users
  
  get 'edit_password', to: 'users#edit_password'

  root 'posts#index'

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :user_name, presence: true, length: { minimum: 4, maximum: 12 }

  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  has_attached_file :avatar, styles: { medium: '152x152#' }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  acts_as_followable
  acts_as_follower
  acts_as_liker
  acts_as_mentionable
  acts_as_mentioner
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :only_allow_super_user
  before_action :set_user, only: [:show, :edit, :edit_password, :update, :destroy]
  
  # GET /xsers
  # GET /xsers.json
  def index
    @users = User.all
  end

  # GET /xsers/1
  # GET /xsers/1.json
  def show
  end

  # GET /xsers/new
  def new
    @user = User.new
  end

  # GET /xsers/1/edit
  def edit
  end

  # GET /xsers/1/edit
  def edit_password
  end

  # POST /xsers
  # POST /xsers.json
  def create
    @user = User.new(xser_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xsers/1
  # PATCH/PUT /xsers/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xsers/1
  # DELETE /xsers/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def only_allow_super_user
      authenticate_user!
      redirect_to root_path, :notice => "Not allowed!" and return unless current_user.is_super_user || (@user && (@user == current_user))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :email, :is_super_user, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_name %>
    <%= f.input :email %>
    <%= f.input :is_super_user if current_user.is_super_user %>
  </div>
  
  <%= link_to "Edit password", edit_password_path(id: @user.id) %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_password.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<div class="container">
  <div class="row">

    <%= render 'form' %>
    
    <%= link_to 'Show', @user %> |
    <%= link_to 'Back', users_path %>
    </div>
</div>

app/views/users/edit_password.html.erb
<h1>Editing User Password</h1>
<div class="container">
  <div class="row">

    <%= render 'password' %>
    
    <%= link_to 'Show', @user %> |
    <%= link_to 'Back', users_path %>
    </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">

    <h1>Listing Users</h1>
    
    <table>
      <thead>
        <tr>
          <th>User name</th>
          <th>Email</th>
          <th>Is super user</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.user_name %></td>
            <td><%= user.email %></td>
            <td><%= user.is_super_user %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <br>
    
    <%= link_to 'New User', new_user_path %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>
<div class="container">
  <div class="row">

    <%= render 'form' %>
    
    <%= link_to 'Back', users_path %>

    </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <p id="notice"><%= notice %></p>
    
    <p>
      <strong>User name:</strong>
      <%= @user.user_name %>
    </p>
    
    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>
    
    <p>
      <strong>Is super user:</strong>
      <%= @user.is_super_user %>
    </p>
    
    <%= link_to 'Edit', edit_user_path(@user) %> |
    <%= link_to 'Back', users_path %>
  </div>
</div>