config/routes.rb
Rails.application.routes.draw do
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'

  devise_for :users, :controllers => { 
    registrations: 'registrations',
    invitations: "invitations" 
  }

  resources :users
  
  get 'edit_password', to: 'users#edit_password'

  root 'posts#index'

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :user_id, presence: true
  validates :image, presence: true
  validates :caption, length: { minimum: 3, maximum: 300 }

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
  acts_as_likeable

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC').page params[:page]
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to root_path
    else
      flash[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to root_path
    else
      flash[:alert] = "Update failed.  Please check the form."
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Your post has been deleted."
    redirect_to root_path
  end

  def like
    if @post.liked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owned_post
    unless current_user == @post.user || current_user.is_super_user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 8
    count_likers(votes)
  end

  def liked_post(post)
    return 'glyphicon-heart' if current_user.voted_for? post
    'glyphicon-heart-empty'
  end

  private

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end

  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' likes this'
  end
end

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_image_select(@post) %>
        <%= simple_form_for @post, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <h4>Upload an image:</h4>
              <%= f.input :image, label: false, input_html: { onChange: 'loadFile(event)' } %>
            </div>
            <div class="form-group text-center">
              <%= f.input :caption, label: false, placeholder: 'Add your caption' %>
            </div>
            <div class="form-group text-center">
              <%= f.button :submit, class: 'btn-success btn-block' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_likes.html.erb
<div class="likes" id="likes_<%= post.id %>">
  <%= display_likes post %>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
      </div>
      <div class="time-ago">
        <%= time_ago_in_words post.created_at %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'),post_path(post) %>
    </div>
    <div class="post-bottom">
      <%= render 'posts/likes', post: post %>
      <div class="caption">
        <div class="caption-content">
          <div class="user-name">
            <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
          </div>
          <%= post.caption %>
          <div class="comments" id="comments_<%= post.id %>">
            <% if post.comments.any? %>
              <%= render post.comments.first(4), post: post %>
              <% unless post.comments.count <= 4 %>
                <div class="paginator" id="#comments-paginator-<%= post.id %>">
                  <%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', id: "more_comments_#{post.id}", data: {post_id: "#{post.id}", type: "html", value: "#{post.comments.count}"} %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="comment-like-form row">
      <div class="col-sm-1 like-button">
        <%= link_to '', like_post_path(post.id), remote: true, id: "like_#{post.id}", class: "like glyphicon #{liked_post post}" %>
      </div>
      <div class="comment-form col-sm-11">
        <%= form_for([post, post.comments.build], remote: true) do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}", data: { post_id: "#{post.id}", value: "#{post.comments.count}" } %>
          <%= f.submit 'New Comment', class: 'comment-submit-button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_posts.html.erb
<%= render @posts %>

app/views/posts/edit.html.erb
<%= render 'form' %>
<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", root_path %>
</div>

app/views/posts/index.html.erb
<div id="posts">
  <%= render 'posts' %>
</div>
<div class="text-center" id="paginator">
  <%= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more' %>
</div>

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render @posts)%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.erb
<%= render "form"  %>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<div class="text-center edit-links">
  <% if @post.user.id == current_user.id || current_user.is_super_user %>
    <%= link_to "Cancel", posts_path %>
    |
    <%= link_to "Edit Post", edit_post_path(@post) %>
  <% else %>
    <%= link_to "Cancel", root_path %>
  <% end %>
</div>