config/routes.rb
Rails.application.routes.draw do
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'

  devise_for :users, :controllers => { 
    registrations: 'registrations',
    invitations: "invitations" 
  }

  resources :users
  
  get 'edit_password', to: 'users#edit_password'

  root 'posts#index'

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Catstagram", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= render 'notifications/notification_dropdown' %>
          </li>
          <li>
            <%= link_to "New Post", new_post_path %>
          </li>
          <li>
            <%= link_to "Profile", profile_path(user_name: current_user.user_name)  %>
          </li>
          <% if current_user.is_super_user %>
            <li>
              <%= link_to "Invite", new_user_invitation_path %>
            </li>
            <li>
              <%= link_to "Users", users_path %>
            </li>
          <% end %>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Photogram</title>
    <meta charset="utf-8"/>
    <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
    <link href='https://fonts.googleapis.com/css?family=Acme' rel='stylesheet'>    

  </head>
</html>
<body>
  <%= render 'layouts/navbar' %>
  <% flash.each do |name, msg| %>
    <div class="container"></div>
    <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
  <% end %>
  <%= yield %>
</body>